"""Tech stack recommendations, ARCHITECTURE.md generation, and interface review."""

import re
from pathlib import Path

from git_plan import commit_planning_docs
from claude_runner import call_claude_cli as call_claude
from ui import hr, header
from project_context import ARCHITECTURE_MD, _project_summary, _stack_summary


# ---------------------------------------------------------------------------
# Phase 2 — tech stack recommendations
# ---------------------------------------------------------------------------

TECH_STACK_PROMPT = """\
You are a senior software architect helping a developer choose a tech stack.

Here is their project definition:

{summary}

Your job:
1. Identify the distinct components this project likely needs \
(e.g. CLI, frontend, backend API, database, auth, background jobs, deployment, etc.).
2. For each component, recommend one specific technology or framework.
3. Give a single-sentence rationale for each choice.
4. Flag any components where the choice is particularly opinionated or has a meaningful \
alternative — mark those with "(alt: X)" after the rationale.

Prefer boring, proven choices. Only recommend something newer/exotic if the project \
clearly benefits from it.

Format exactly like this (one component per line, no extra text before or after):

1. **Component Name**: Technology — rationale. (alt: Alternative) [optional]
2. **Component Name**: Technology — rationale.
...
"""


def stream_recommendations(sections: dict[str, str], repo_context: str | None = None) -> str:
    summary = _project_summary(sections, repo_context)

    print("\n" + hr("="))
    print("  Step 2: Tech Stack Recommendations")
    print(hr("="))
    print("\n  Analyzing your project...\n")
    return call_claude(TECH_STACK_PROMPT.format(summary=summary), max_tokens=1024)


def parse_components(raw: str) -> list[dict]:
    components = []
    pattern = re.compile(
        r"\d+\.\s+\*\*(.+?)\*\*:\s+(.+?)\s+—\s+(.+?)(?:\s+\(alt:\s+(.+?)\))?\s*$"
    )
    for line in raw.splitlines():
        m = pattern.match(line.strip())
        if m:
            components.append({
                "name": m.group(1).strip(),
                "tech": m.group(2).strip(),
                "rationale": m.group(3).strip(),
                "alt": m.group(4).strip() if m.group(4) else None,
            })
    return components


def confirm_tech_stack(raw_recs: str) -> list[dict] | None:
    components = parse_components(raw_recs)

    if not components:
        print("  Could not parse recommendations — showing raw output above.")
        print("  Edit ARCHITECTURE.md manually after this run.")
        return None

    header("Review Tech Stack — confirm or override each component")
    print("\n  For each component: press Enter to accept, or type your preferred technology.\n")

    confirmed: list[dict] = []
    for c in components:
        alt_hint = f"  (alt: {c['alt']})" if c["alt"] else ""
        print(f"\n  {c['name']}: {c['tech']}{alt_hint}")
        print(f"    {c['rationale']}")
        override = input("  Accept? [Enter] or type replacement: ").strip()
        if override:
            c = {**c, "tech": override, "rationale": "(user override)"}
        confirmed.append(c)

    return confirmed


# ---------------------------------------------------------------------------
# Phase 3 — write ARCHITECTURE.md
# ---------------------------------------------------------------------------

ARCH_PROMPT = """\
You are a senior software architect. Write a concise ARCHITECTURE.md for this project.

Project definition:
{summary}

Agreed tech stack:
{stack}

Include these sections:
1. **Overview** — 1-2 sentences
2. **Components** — markdown table: Component | Technology | Directory | Purpose
3. **Component Details** — one subsection per component with directory path and scope (1-2 sentences)
4. **Interfaces** — APIs and data contracts between components; use TODO where not yet known

Rules:
- Use the exact technology names agreed above.
- Suggest sensible directory paths (e.g. `frontend/`, `api/`, `db/`).
- Keep each section tight. No fluff.
- Start the document with: \
`> Generated by planning/plan.py. Edit manually or re-run the planner to regenerate.`
"""


def write_architecture(sections: dict[str, str], components: list[dict], repo_context: str | None = None) -> None:
    summary = _project_summary(sections, repo_context)
    stack = "\n".join(
        f"- **{c['name']}**: {c['tech']} — {c['rationale']}" for c in components
    )

    header("Generating ARCHITECTURE.md")
    print()

    content = call_claude(ARCH_PROMPT.format(summary=summary, stack=stack), max_tokens=2048)
    ARCHITECTURE_MD.write_text(content)
    print(f"\n\n  Written to {ARCHITECTURE_MD}\n")
    commit_planning_docs([ARCHITECTURE_MD], "planning: update ARCHITECTURE.md")


# ---------------------------------------------------------------------------
# Phase 3b — interface review
# ---------------------------------------------------------------------------

INTERFACE_EXTRACT_PROMPT = """\
You are a senior software architect reviewing a project architecture.

ARCHITECTURE.md:
{architecture}

Extract and display all critical interfaces that need explicit design agreement. Cover:
- REST / GraphQL / WebSocket endpoints: method, path, key request + response fields
- JSON schemas: event shapes, DTOs, config files
- Database schemas: tables or collections with key columns / fields and types
- Inter-service contracts: message queues, internal RPC, pub/sub topics
- External integrations: third-party APIs being called or consumed

Format each interface as:

### [Type] Interface Name
<brief schema, signature, or field list — use a code block where helpful>
_TODOs or open questions, if any_

Skip categories that don't apply. Keep entries tight — enough detail to spot gaps, \
not a full spec. Do not include anything not already implied by the architecture.
"""

INTERFACE_APPLY_CORRECTION_PROMPT = """\
You are updating a software architecture document based on user feedback.

Current ARCHITECTURE.md:
{architecture}

User correction:
{correction}

Apply this correction to the architecture. Update interface definitions, schemas, \
endpoint signatures, component details, or any other section as the correction requires. \
Preserve everything not mentioned.

Return the complete updated ARCHITECTURE.md. Begin with the \
`> Generated by planning/plan.py` header line.
"""


def review_interfaces() -> None:
    print("\n" + hr("="))
    print("  Step 3b: Interface Review")
    print(hr("="))
    print("\n  Extracting critical interfaces from ARCHITECTURE.md...\n")

    while True:
        architecture = ARCHITECTURE_MD.read_text() if ARCHITECTURE_MD.exists() else ""
        call_claude(
            INTERFACE_EXTRACT_PROMPT.format(architecture=architecture),
            max_tokens=2048,
            print_output=True,
        )
        print()

        print(f"  {hr('·')}")
        print("  Enter a correction in plain English, or press Enter when interfaces look good.")
        print(f"  {hr('·')}\n")

        lines: list[str] = []
        while True:
            line = input("  > ")
            if not line:
                break
            lines.append(line)

        if not lines:
            commit_planning_docs([ARCHITECTURE_MD], "planning: finalize interfaces in ARCHITECTURE.md")
            print("  Interfaces accepted.\n")
            break

        correction = "\n".join(lines)
        print("\n  Applying correction...\n")
        updated = call_claude(
            INTERFACE_APPLY_CORRECTION_PROMPT.format(
                architecture=architecture,
                correction=correction,
            ),
            max_tokens=3000,
            print_output=False,
        )
        ARCHITECTURE_MD.write_text(updated)
        print("  ARCHITECTURE.md updated — reviewing again...\n")
