"""Phase 6: task manifest generation, per-task review, validation, and TASKS.md."""

import re
from pathlib import Path

from git_plan import commit_planning_docs
from claude_runner import call_claude_cli as call_claude
from ui import hr, header, timed_call
from project_context import _project_summary, _stack_summary
from schema import TASK_FIELDS, field_descriptions, prompt_example, validate_all
from task_graph import parse_task_blocks, verify_task_graph


TASKS_MD = Path("TASKS.md")

_TASK_MANIFEST_PROMPT_TEMPLATE = """\
You are a senior software architect generating a complete task manifest with a dependency graph.

Project:
{{summary}}

Tech stack:
{{stack}}

Workstreams and their preliminary tasks:
{{ws_tasks}}

Produce an enriched, sequenced task list across ALL workstreams. Order tasks roughly by \
when they can start (blockers first).

Field definitions — every task MUST include every field, even if the value is —:
{field_defs}

Output each task as a block separated by a line containing only ---
Use exactly the field keys shown below. Do not add or omit any fields.

Example task block:
{example}

---

(continue for all tasks)
"""

TASK_MANIFEST_PROMPT = _TASK_MANIFEST_PROMPT_TEMPLATE.format(
    field_defs=field_descriptions(),
    example=prompt_example(),
)


def _ws_tasks_text(ws_list: list[dict]) -> str:
    lines = []
    for w in ws_list:
        lines.append(f"\n{w['id']} — {w['name']}: {w['scope']}")
        for t in w.get("tasks", []):
            lines.append(f"  - [{t['priority']}] {t['name']} ({t['estimate']})")
    return "\n".join(lines)


def _print_task_table(tasks: list[dict]) -> None:
    print(f"\n  {'ID':<6} {'WS':<6} {'Crit':<5} {'Est':<5}  Task")
    print(f"  {hr('─', 58)}")
    for t in tasks:
        ws_short = t.get("workstream", "").split("—")[0].strip()
        human_flag = "  *" if t.get("human", "—") != "—" else ""
        print(f"  {t['ID']:<6} {ws_short:<6} {t.get('criticality',''):<5} {t.get('estimate',''):<5}  {t['name']}{human_flag}")
    print(f"\n  * = requires human action (AI cannot do this)\n")


def write_tasks_md(tasks: list[dict]) -> None:
    p0 = sum(1 for t in tasks if t.get("criticality") == "P0")
    p1 = sum(1 for t in tasks if t.get("criticality") == "P1")
    p2 = sum(1 for t in tasks if t.get("criticality") == "P2")
    human_count = sum(1 for t in tasks if t.get("human", "—") != "—")

    lines: list[str] = [
        "> Generated by planning/plan.py. Edit manually or re-run the planner to regenerate.\n",
        "# Tasks\n",
        "## Summary\n",
        f"**Total:** {len(tasks)}  |  "
        f"**P0:** {p0}  |  **P1:** {p1}  |  **P2:** {p2}  |  "
        f"**Human steps:** {human_count}  |  **Complete:** 0\n",
        "## Index\n",
        "| ID | Workstream | Task | Crit | Est | Status |",
        "|----|-----------|------|------|-----|--------|",
    ]

    for t in tasks:
        ws_short = t.get("workstream", "").split("—")[0].strip()
        lines.append(
            f"| {t['ID']} | {ws_short} | {t['name']} | {t.get('criticality','')} "
            f"| {t.get('estimate','')} | {t.get('status', 'todo')} |"
        )

    lines.append("\n## Task Details\n")

    for t in tasks:
        lines.append(f"### {t['ID']} · {t['name']}\n")
        for f in TASK_FIELDS:
            if f.key in ("ID", "name"):
                continue
            value = t.get(f.key, f.default or "—")
            if f.key == "human" and value != "—":
                lines.append(f"> **{f.label}:** {value}\n")
            else:
                lines.append(f"**{f.label}:** {value}  ")
        lines.append("")

    TASKS_MD.write_text("\n".join(lines))
    print(f"  Written to {TASKS_MD}\n")
    commit_planning_docs([TASKS_MD], "planning: update TASKS.md")


_REVIEW_FIELDS = [
    ("estimate",    "Time Estimate",       "How long will this realistically take?"),
    ("depends",     "Depends On",          "Task IDs this cannot start until they are done (space-separated)"),
    ("unlocks",     "Unlocks / Blocks",    "Task IDs that are unblocked when this is done (space-separated)"),
    ("acceptance",  "Success Criteria",    "Observable, specific definition of done"),
    ("tricky",      "Risks & Focus Areas", "What is subtle, likely to go wrong, or easy to miss when verifying?"),
    ("human",       "Human Required",      "Actions an AI cannot do: billing approval, API key creation in a dashboard, OAuth app registration, provisioning, app store submissions. Blank if AI can fully automate."),
]


def _review_tasks(tasks: list[dict]) -> list[dict]:
    print(f"\n  {hr('=')}")
    print("  Task Review — verify each task's key fields")
    print(f"  {hr('=')}")
    print(f"\n  {len(tasks)} task(s) to review.")
    print("  For each field: press Enter to accept Claude's value, or type to override.\n")

    ans = input("  Review tasks now? [Y/n]: ").strip().lower()
    if ans == "n":
        print("  Skipped — using Claude's generated values.\n")
        return tasks

    for i, task in enumerate(tasks, 1):
        print(f"\n  {hr('─')}")
        ws_short = task.get("workstream", "").split("—")[0].strip()
        print(f"  [{i}/{len(tasks)}]  {task['ID']}  ·  {task.get('name', '')}  [{ws_short}]")
        print(f"  {hr('─')}")

        for key, label, description in _REVIEW_FIELDS:
            current = task.get(key, "—") or "—"
            print(f"\n  {label}")
            print(f"  {description}")
            print(f"  Current: {current}")
            val = input("  > ").strip()
            if val:
                task[key] = val

    print(f"\n  Review complete.\n")
    return tasks


def _validate_and_fix(tasks: list[dict]) -> list[dict]:
    issues = validate_all(tasks)
    if not issues:
        return tasks

    print(f"\n  {len(issues)} task(s) have blank required fields.\n")
    print("  For each: type a value to fill it in, or press Enter to leave as \"\".\n")

    task_map = {t["ID"]: t for t in tasks}
    for tid, errors in issues.items():
        t = task_map[tid]
        print(f"  {hr('·')}")
        print(f"  {tid} — {t.get('name', '')}")
        for err in errors:
            key_m = re.match(r"\s*(\w+)\s+\(", err)
            if not key_m:
                continue
            key = key_m.group(1)
            f = next((x for x in TASK_FIELDS if x.key == key), None)
            if not f:
                continue
            print(f"\n    {f.label}: {f.description}")
            val = input(f"    Value (Enter = \"\"): ").strip()
            t[key] = val

    return tasks


def generate_task_manifest(
    sections: dict[str, str], components: list[dict], ws_list: list[dict],
    repo_context: str | None = None,
) -> list[dict] | None:
    print("\n" + hr("="))
    print("  Step 6: Task Manifest")
    print(hr("="))
    print("\n  Building full task graph with dependencies and human requirements...")
    print("  (Claude reasons across all workstreams — typically takes 1–3 minutes)\n")

    summary = _project_summary(sections, repo_context)
    stack = _stack_summary(components)
    ws_tasks = _ws_tasks_text(ws_list)

    raw = timed_call(
        lambda: call_claude(
            TASK_MANIFEST_PROMPT.format(summary=summary, stack=stack, ws_tasks=ws_tasks),
            max_tokens=4096,
            print_output=False,
        ),
        "Generating task manifest",
    )

    tasks = parse_task_blocks(raw)
    if not tasks:
        print("  Could not parse task manifest. Check plan.py output above.\n")
        return None

    _print_task_table(tasks)

    print("  Review the task list above.")
    print("  Enter task IDs to remove (e.g. 'T004 T009'), or Enter to accept all.\n")
    removes_raw = input("  > ").strip().upper()
    if removes_raw:
        drop = set(removes_raw.split())
        tasks = [t for t in tasks if t["ID"] not in drop]
        for i, t in enumerate(tasks, 1):
            old_id = t["ID"]
            new_id = f"T{i:03d}"
            if old_id != new_id:
                for other in tasks:
                    for f in ("depends", "unlocks"):
                        if other.get(f):
                            other[f] = other[f].replace(old_id, new_id)
                t["ID"] = new_id

    tasks = _review_tasks(tasks)
    tasks = _validate_and_fix(tasks)
    tasks = verify_task_graph(tasks)

    header("Writing TASKS.md")
    write_tasks_md(tasks)
    return tasks
